<?php
namespace app\component;
use yii;
use yii\web\Controller;
class MyController extends Controller
{
    public function init()
    {

        $this->layout='main';
        parent::init(); // TODO: Change the autogenerated stub
       
    }
}